### ISSUE TITLE
add <hostname>.local domain name as trusted domain by default

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud-snap/nextcloud-snap#1659]
according to the [readme](https://github.com/nextcloud/nextcloud-snap#how-to-use) by default nextcloud should be reachable at `<hostname>.local` but this is not one of the default trusted domains.

is it possible to have `<hostname>.local` trusted by default alongside `localhost`?

**Comment by scubamuc** [comment]
Hi, fond this in Wiki:

![grafik](https://user-images.githubusercontent.com/54933878/109648712-3c5e8580-7b5b-11eb-9026-7e5d371547f3.png)

**Comment by Fuseteam** [comment]
> Hi, found this in Wiki:
> 
> ![grafik](https://user-images.githubusercontent.com/54933878/109648712-3c5e8580-7b5b-11eb-9026-7e5d371547f3.png)

uh yes but that too is not a trusted domain by default

**Comment by jorkzijlstra** [comment]
That would be nice indeed.

As a workaround I have been adding the needed hostnames manually via an ansible step:

Variable
```
nextcloud_server_hostnames:
  - {{ replace with hostname }}
  - {{ replace with hostname }}.local
  - {{ ip address }}
```
Ansible step:
```
- name: Add hostnames, domains, and IP addresses as trusted domains {1..3}
  shell: nextcloud.occ config:system:set trusted_domains {{ my_idx }} --value="{{ item }}"
  loop: "{{ nextcloud_server_hostnames }}"
  loop_control:
    index_var: my_idx
  notify:
    - nextcloud restart
```
