### ISSUE TITLE
How to run fresh setups on ubuntu 24.04 | might benefit as documentation improvements

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2888]
Just sharing my story to clarify some of the inconsistencies in the wiki while setting up the last 3 dedicated nextcloud instances on fresh Ubuntu server 24.04 setups.

All setups are fairly the same. always behind bunkerweb.com as the reverse proxy and web application firewall of my choice.

Nextcloud runs on port 9001, lets encrypt disabled.
I use ufw. You might skip this if you have other ways.

Here we go...

1- Setup ubuntu or ubuntu server with a static ip.

```txt
if you don't know how to do this, what are you even doing reading this? 😉 
```

2- Setup ufw and nextcloud base:
```bash
sudo apt install ufw # I dont quite like the snap ufw version as today
# enable ssh replace local networks accordingly
sudo ufw --force enable; sudo ufw allow from 192.168.1.0/24 to any port 22 proto tcp; sudo ufw --force enable
sudo ufw allow from 192.168.1.0/24 to any port 9001 proto tcp # nextcloud
# you might have to do also a 172... rule if bunkerweb is on the same host
sudo ufw allow from 172.16.0.0/12 to any port 9001 proto tcp # nextcloud
# install nextcloud
sudo snap install nextcloud
# install required libraries
sudo apt install fontconfig libfuse2 glibc-source
# change port
sudo snap set nextcloud ports.http=9001
# disable certs management
sudo nextcloud.disable-https lets-encrypt
sudo snap stop --disable nextcloud.renew-certs
```

Now. GOTO the nextcloud fresh url and sign up... do the initial admin account creation.

```txt
http://localhost:9001
or 
http://ip.of.the.host:9001
```

3- Deeper nextcloud setup: Helps with the initial warnings and allows reverse proxy work.

```bash
sudo nextcloud.occ config:system:set --type=bool --value=false simpleSignUpLink.shown
sudo nextcloud.occ config:system:set --type=bool --value=false allow_local_remote_servers
sudo nextcloud.occ config:system:set --type=bool --value=false allow_user_to_change_display_name
sudo nextcloud.occ config:system:set --type=bool --value=false profile.enabled

sudo nextcloud.occ config:system:set overwritehost --value="cloud.domain.tld"
sudo nextcloud.occ config:system:set overwriteprotocol --value="https"
sudo nextcloud.occ config:system:set overwrite.cli.url --value="https://cloud.domain.tld"
sudo nextcloud.occ config:system:set trusted_domains 0 --value="cloud.domain.tld"
sudo nextcloud.occ config:system:set trusted_proxies 0 --value="192.168.1.12/32"
sudo nextcloud.occ config:system:set trusted_proxies 1 --value="172.16.0.0/12" # you need this if bunker web runs in the same server of nextcloud otherwise skip
```

If you want to have a working OFFICE + COLLABORA COMMUNITY working you HAVE TO REBOOT.

```bash
sudo reboot # if you don't reboot the office server will not work. so reboot at least once to finish the initial setup
```

4- Other nextcloud trivial settings:

```bash
sudo nextcloud.occ config:system:set default_phone_region --value=“NZ” # set your base country
sudo nextcloud.occ db:add-missing-indices
sudo nextcloud.occ maintenance:repair --include-expensive
```

5- setup bunker web for nctalk and ncoffice in the same host or a separated host, make sure to apply ufw inbound/outbound rules accordingly between hosts.

```bash
sudo snap install docker
```

Create and run this compose file. Make sure you edit ports and others if necessary. defaults run 8080 and 8443 as inbound forward/trough your gateway. 

```
name: 'some-name'

services:

  bunkerweb:
    image: bunkerity/bunkerweb:1.5.10
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - MULTISITE=yes
      - SEND_ANONYMOUS_REPORT=no
      - SERVER_NAME=cloud.domain.tld
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_BUFFERING=no
      - AUTO_LETS_ENCRYPT=yes
      - DENY_HTTP_STATUS=444 # over 403 default
      - USE_CLIENT_CACHE=no
      - DISABLE_DEFAULT_SERVER=yes
      - SERVE_FILES=no
      - X_FRAME_OPTIONS=SAMEORIGIN
      - USE_GZIP=yes
      - BAD_BEHAVIOR_STATUS_CODES=400 401 403 405 444
      - MAX_CLIENT_SIZE=100m # change this if necessary for file uploads 
      - LIMIT_REQ_RATE=100r/s
      # domain
      - cloud.domain.tld_EMAIL_LETS_ENCRYPT=email@forletsencrypt.tld
      - cloud.domain.tld_REVERSE_PROXY_HOST=http://ipofnextcloudhost:9001
      - cloud.domain.tld_USE_BAD_BEHAVIOR=yes
      - cloud.domain.tld_ALLOWED_METHODS=GET|POST|HEAD|COPY|DELETE|LOCK|MKCOL|MOVE|PROPFIND|PROPPATCH|PUT|UNLOCK|OPTIONS|REPORT
      - cloud.domain.tld_CONTENT_SECURITY_POLICY_REPORT_ONLY=yes
      - cloud.domain.tld_PERMISSIONS_POLICY=accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(self), cross-origin-isolated=(), display-capture=(self), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(self), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), web-share=(), xr-spatial-tracking=()
      - cloud.domain.tld_FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; battery 'none'; camera 'self'; display-capture 'self'; document-domain 'none'; encrypted-media 'none'; execution-while-not-rendered 'none'; execution-while-out-of-viewport 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; layout-animation 'none'; legacy-image-formats 'none'; magnetometer 'none'; microphone 'self'; midi 'none'; navigation-override 'none'; payment 'none'; picture-in-picture 'none'; publickey-credentials-get 'none'; speaker-selection 'none'; sync-xhr 'none'; unoptimized-images 'none'; unsized-media 'none'; usb 'none'; screen-wake-lock 'none'; web-share 'none'; xr-spatial-tracking 'none';
      - |
        cloud.domain.tld_CUSTOM_CONF_SERVER_HTTP_wellknowns=
        location /.well-known/carddav {return 301 https://cloud.domain.tld/remote.php/dav/;}
        location /.well-known/caldav {return 301 https://cloud.domain.tld/remote.php/dav/;}
        location /.well-known/webfinger {return 301 https://cloud.domain.tld/index.php/.well-known/webfinger;}
        location /.well-known/nodeinfo {return 301 https://cloud.domain.tld/index.php/.well-known/nodeinfo;}
      - |
        cloud.domain.tld_CUSTOM_CONF_MODSEC_CRS_nextcloud=
        SecAction "id:900130,phase:1,nolog,pass,t:none,setvar:tx.crs_exclusions_nextcloud=1"
        SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:'tx.allowed_methods=GET POST HEAD COPY DELETE LOCK MKCOL MOVE PROPFIND PROPPATCH PUT UNLOCK OPTIONS REPORT'"
      - |
        cloud.domain.tld_CUSTOM_CONF_MODSEC_nextcloud=
        SecRule REQUEST_URI "@contains /remote.php/" "phase:1,id:2000,nolog,pass,ctl:ruleEngine=Off"
        SecRule REQUEST_URI "@contains richdocuments" "phase:1,id:2001,nolog,pass,ctl:ruleEngine=Off"
    networks:
      bw-universe:
      bw-services:

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.10
    restart: unless-stopped
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:0.1.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

Allow gateway port forward for inbound 80 in router to 8080 bunkerweb host ip and 443 router to 8443 bunker web host ip

You need to do this so bunkerweb can handle the traffic and lets-encrypt internal functionality.

Open browser.

https://cloud.domain.tld and you should have a secure working nextcloud.
