### ISSUE TITLE
Talk: High performance backend?

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2920]
The Docker AIO solution has optional support for a high performance back-end.

Anyway we can implement this as included in the snap version?

**Comment by scubamuc** [comment]
hey @sbe-arg, did you see this [HPB client-push configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-HPB-client-push-for-Nextcloud-snap)? give it a shot.

**Comment by sbe-arg** [comment]
Ill give it a go and confirm.

**Comment by scubamuc** [comment]
@sbe-arg, yeah I'd be interested in a Talk-HPB myself. I had a TURN Server running a while back (https://www.c-rieger.de/nextcloud-und-coturn/)... that worked fine until I moved my instance into a container with a separate reverse proxy.

I know that @Pilzinsel64 runs a turn-server successfully. maybe he has some info?

**Comment by sbe-arg** [comment]
I used to run AIO and rarely needed to talk to more than 1 person but now I have been setting up a few servers that require a few remote people so I'm looking for cleaner ways to get the Talk-HPB up and running.

Either with docker as sidecar, within snap or native.

**Comment by scubamuc** [comment]
@sbe-arg I've failed miserably getting coturn to run in docker with my reverse proxy... so anything you figure out would certainly be great.

**Comment by sbe-arg** [comment]
There is https://hub.docker.com/r/coturn/coturn for running the TURN but In my test case while using these for example https://www.metered.ca/tools/openrelay/#turn-server-for-nextcloud-talk it works most of the time without issues.

But the server itself regardless of how big the serve is (I have tried on Xeon 12 core, 64GB ram as well as a tiny 2 Core i3 2gb ram) it won't allow more than 5-6 people to work properly. Some will not connect to others randomly if they reconnect it might work for the person that did not work before all randomly so is not necessarily the TURN setting I believe (because I tried the coturn docker and made no diff with the Metered openrelay) It looks like is a nextcloud talk limitation that needs a the HPB for more people. Would be nice to be able to bypass this limitation some how.

I think it can also be tested by trying to run a local meeting with more than 10 people u get similar results if not using HPB. (I don't have that many people available for testing hahaha)

**Comment by Pilzinsel64** [comment]
First, to clarify, TURN != Talk HPB. While TURN acts as relay to bypass firewalls etc. the Talk High Performance Backend acts as centralized server where all clients connect to and is an additional and component and has nothing todo with TURN.

The minimum should be a working TURN server for a Nextcloud instance with active Talk app. I usually use this two links for my setup:
- https://nextcloud-talk.readthedocs.io/en/latest/TURN/
- https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794

Talk HPB can be installed additionaly and should only be installed on servers with good performance and very good internet. As soon as Talk HBP is configured in Nextcloud, each client will connect to the server instead to each other client.

However, this is nothing we can or should ship within the core snap package. But few years back I got it running together with my private snap instance. I remember you can use the same script that is available in the VM repo. Might be this one, but can't remember correctly: https://github.com/nextcloud/vm/blob/main/apps/talk.sh

**Comment by sbe-arg** [comment]
The AIO image includes Talk HPB as optional https://github.com/nextcloud/all-in-one?tab=readme-ov-file#nextcloud-all-in-one 

Although very undocumented

**Comment by sbe-arg** [comment]
As stated.
My problem is not currently STUN or TURN setups is that the built-in talk app does not support more than 3-5 users regardless of its compute power.

So would be nice to find a simpler way to setup the Talk HPB. Maybe a dedicated snap package?

**Comment by scubamuc** [comment]
@sbe-arg see this https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794/109

For TURN service:
 https://www.metered.ca/tools/openrelay/

**Comment by scubamuc** [comment]
@sbe-arg see this for self hosted signaling server: https://github.com/strukturag/nextcloud-spreed-signaling/blob/master/docker/README.md

**Comment by sbe-arg** [comment]
Not bad but is not clear how to set it up.

Ill experiment a bit.

In and ideal world we could have a snap Talk HPB

**Comment by scubamuc** [comment]
@sbe-arg
> In and ideal world we could have a snap Talk HPB

see https://github.com/nextcloud/spreedme-snap/ available snap https://snapcraft.io/spreedme

**Comment by Pilzinsel64** [comment]
> see https://github.com/nextcloud/spreedme-snap/ available snap https://snapcraft.io/spreedme

That's an old repo, no changes since 7 years.

**Comment by scubamuc** [comment]
@Pilzinsel64 ✔ yeah, so much for the "ideal world" 🤣

**Comment by sbe-arg** [comment]
But imagine the traction XD

If you deploy

Snap nextcloud
Snap nextcloud-hpb-files
Snap nextcloud-hpb-talk

In any cluster form you get a decent setup for small to mid (up to 20+30ppl) setup in minutes.

**Comment by pachulo** [comment]
> Snap nextcloud
> Snap nextcloud-hpb-files

Well, that part [is already covered](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-HPB-client-push-for-Nextcloud-snap), isn't it? 😄

**Comment by scubamuc** [comment]
@pachulo 
> Well, that part [is already covered](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-HPB-client-push-for-Nextcloud-snap), isn't it? 😄

nope, thats files HPB... 🤔

**Comment by scubamuc** [comment]
@pachulo 
> Well, that part [is already covered](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-HPB-client-push-for-Nextcloud-snap), isn't it? 😄

that didn't work for me 😒

**Comment by scubamuc** [comment]
@pachulo 
dunno, tried this for corporate instance and failed... personal pod. haven't tried. guess its a reverse proxy issue? 🙄

**Comment by Pilzinsel64** [comment]
@scubamuc Probably. I can take a look at the Nextcloud instance and HPB configuration next week (Tuesday) if you want. Just need SSH access and an admin account like the last time. Would that be possible? I know I told you to look at it earlier but was busy and forgot. Sorry. 🙈

**Comment by scubamuc** [comment]
@Pilzinsel64 no problem... 

no access to corporate instance i'm afraid, maybe signal or teamviewer? u got my signal right?

**Comment by Pilzinsel64** [comment]
@scubamuc I sent you an email and meeting invitation via my company email.

**Comment by scubamuc** [comment]
@sbe-arg this is what I have so far --> documented [here](https://github.com/scubamuc/wiki-md/blob/scubamuc-wiki/Nextcloud-signalling.md) 

since snap is not "stackable" we could try dockerizing the talk-hpb? 
can't get the stack to work yet though... do you wanna try?

**Comment by scubamuc** [comment]
@sbe-arg also experimenting with https://eturnal.net dockerized

**Comment by sbe-arg** [comment]
But still @scubamuc you are focusing on STUN TURN setups and those are no HPBs.
It is a bit noisy for this issue to have so many TURN links IMO.

**Comment by scubamuc** [comment]
Hey @sbe-arg if the docker runs a service on the same host as the snap, the snap should be able to connect to the service in a standard fashion.

assuming you run docker on the same host, they should run fine side by side. you'll simply have a docker container and a snap "container" both running in their own sandbox. 

> Can we run docker containers inside snap? 

no that's not possible, but you can run docker as a snap on the container also.

@Pilzinsel64 wdyt

**Comment by sbe-arg** [comment]
https://ubuntu.com/core/docs/docker-snap-image

**Comment by scubamuc** [comment]
@sbe-arg 
> They seem to work fine.

> Maybe we can add them as services and document how to setup the env vars required.

can you share your stack?

**Comment by sbe-arg** [comment]
I know i can run docker along snap.


I'm suggesting we snap the docker setup for and easier setup.

So we can have a snap nextcloud-talk package or alike

**Comment by sbe-arg** [comment]
I'm running a test monster

Snap nextcloud with a hybrid recording and talk hpbs based on this.

Modified the config file and pruned down the yaml compose to the bare min.

Ill do realistic meetings this week to make sure it runs 10 ppl o so.

https://github.com/nextcloud/all-in-one/tree/main/manual-install

**Comment by sbe-arg** [comment]
Tested 5 ppl without issues today.

Ill run a 10+ later this week and share a how to.

(The tricky part is the port and ws forwarding)

Single docker compose.

**Comment by sbe-arg** [comment]
If anyone wants to try this out here are my upstream notes https://github.com/nextcloud/all-in-one/issues/5512#issuecomment-2453549033 

After a few weeks of testing Ill open a pr upstream in case I find more tuneups.

**Comment by scubamuc** [comment]
@sbe-arg thanks for the hard work... job well done

this works for me

**Comment by scubamuc** [comment]
@sbe-arg i'm having issues connecting to the signalling server... using ``https` and ``wss` can't connect?

can you show reverse proxy settings please?

**Comment by sbe-arg** [comment]
I assume you mean wss over https.

Wss is about connection upgrades. But each reverse proxy does this setting differently.

If using nginx you need something like this.


```
location / {
proxy_pass ​http://signaling_host; proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_read_timeout 86400;
}
```

**Comment by sbe-arg** [comment]
in more detail using bunkerweb i use this... they have REVERSE_PROXY_WS https://docs.bunkerweb.io/latest/settings/#reverse-proxy:~:text=will%20be%20proxied.-,REVERSE_PROXY_WS,-no

```
name: 'waf'

services:

  bunkerweb:
    image: bunkerity/bunkerweb:1.5.10
    restart: unless-stopped
    ports:
      - 44080:44080
      - 44443:44443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - HTTP_PORT=44080
      - HTTPS_PORT=44443
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24 192.168.1.0/24
      - MULTISITE=yes
      - SEND_ANONYMOUS_REPORT=no
      - SERVER_NAME=signaling.domain.tld
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_BUFFERING=no
      - AUTO_LETS_ENCRYPT=yes
      - DENY_HTTP_STATUS=444 # over 403 default
      - USE_CLIENT_CACHE=no
      - DISABLE_DEFAULT_SERVER=yes
      - SERVE_FILES=no
      - X_FRAME_OPTIONS=SAMEORIGIN
      - USE_GZIP=yes
      - BAD_BEHAVIOR_STATUS_CODES=400 401 403 405 444
      - MAX_CLIENT_SIZE=100m # 100mb
      - LIMIT_REQ_RATE=1000r/s
      - USE_BAD_BEHAVIOR=yes
      - USE_UI=no
      - BAD_BEHAVIOR_THRESHOLD=60
      - BAD_BEHAVIOR_BAN_TIME=3600
      - AUTO_REDIRECT_HTTP_TO_HTTPS=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - LISTEN_HTTP=yes # needed for lets encrypt
      - ALLOWED_METHODS=GET|POST|PATCH|HEAD|COPY|DELETE|LOCK|MKCOL|MOVE|PROPFIND|PROPPATCH|PUT|UNLOCK|OPTIONS|REPORT
      # signaling
      - signaling.domain.tld_EMAIL_LETS_ENCRYPT=email
      - signaling.domain.tld_REVERSE_PROXY_HOST=http://ip:port
      - signaling.domain.tld_REVERSE_PROXY_WS=yes
    networks:
      bw-universe:
      bw-services:

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.10
    restart: unless-stopped
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:0.1.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker

```
