### ISSUE TITLE
no heic previews

### ISSUE THREAD

**Issue by bsbebbi** [nextcloud-snap/nextcloud-snap#3041]
#### Describe the bug
After uploading heic pictures, there are no previews for those files in the file browser.
(if you do the same with jpg pictures previews are generated)

#### To Reproduce
1. Install a fresh nextcloud snap, leave all defaults as suggested
2. Log in with new userid and password, thus creating a new admin
3. Goto Files -> (e.g) Photos
4. Click 'New' button, upload some images in jpg and heic format
5. See error: for the heic files, there are no previews
#### Expected behavior
previews are generated for jpg and heic files
(didn't test with other formats)

#### Screenshots
not added, so easy to reproduce imho

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  30.0.5snap1  46218  latest/stable  nextcloud✓  -

    $ snap version
snap    2.67
snapd   2.67
series  16
ubuntu  22.04
kernel  5.15.0-130-generic
#### Logs
not added, so easy to reproduce imho

**Comment by scubamuc** [comment]
hey @bsbebbi welcome and thanks for your request

there have been several requests upstream referring to "HEIC" support: https://help.nextcloud.com/search?q=HEIC

this is certainly due to the fact that the snap does not ship "imagick" see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#imagick-php-module-is-not-enabled) and a recent version of "imagick" will be required to generate "HEIC" previews. so you'll have to live with this drawback or use a different install.

this is certainly an upstream issue.  Please Log an issue upstream

> previews are generated for jpg 

your "jpg" issues cannot be reproduced. most default formats will be generated without "imagick"

![Image](https://github.com/user-attachments/assets/7841ad8a-4413-4d70-b591-ae300d39fff0)

**Comment by szaimen** [comment]
Hi, imaginary could be used to enable heic previews: -https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews 
- https://github.com/nextcloud/all-in-one/blob/0e10cfd20b5c102d406f9b8f646563342403ae89/manual-install/latest.yml#L391-L416

**Comment by scubamuc** [comment]
@szaimen thanks for mentioning

so create and run a docker stack for **imaginary** using [Nextcloud AIO image](https://github.com/nextcloud/all-in-one/blob/0e10cfd20b5c102d406f9b8f646563342403ae89/manual-install/latest.yml#L391-L416)

```
  nextcloud-aio-imaginary:
    image: nextcloud/aio-imaginary:latest
    user: "65534"
    init: true
    healthcheck:
      start_period: 0s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 3
    expose:
      - "9000"
    environment:
      - TZ=${TIMEZONE}
      - IMAGINARY_SECRET
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    cap_drop:
      - NET_RAW
    profiles:
      - imaginary
    read_only: true
    tmpfs:
      - /tmp
```

edit config.php and add

```
<?php
'enabledPreviewProviders' => [
    'OC\Preview\MP3',
    'OC\Preview\TXT',
    'OC\Preview\MarkDown',
    'OC\Preview\OpenDocument',
    'OC\Preview\Krita',
    'OC\Preview\Imaginary',
],
'preview_imaginary_url' => 'http://<url of imaginary>',
```

to enable HEIC previews
